#define PJMEDIA_CONF_USE_SWITCH_BOARD 	   1
#define PJMEDIA_CONF_SWITCH_BOARD_BUF_SIZE 2000

#define PJSUA_MAX_CALLS 	256
#define PJSUA_MAX_PLAYERS 	512
#define PJ_IOQUEUE_MAX_HANDLES 	512

#define PJMEDIA_HAS_G711_CODEC		0
#define PJMEDIA_HAS_L16_CODEC		0
#define PJMEDIA_HAS_GSM_CODEC		0
#define PJMEDIA_HAS_SPEEX_CODEC		0
#define PJMEDIA_HAS_ILBC_CODEC		0
#define PJMEDIA_HAS_G722_CODEC		0
#define PJMEDIA_HAS_G7221_CODEC		0
#define PJMEDIA_HAS_OPENCORE_AMRNB_CODEC	0
#define PJMEDIA_HAS_OPUS_CODEC          1
