[logging]
core=1                ; Gateway core logging level: 0-trace (max), 1-debug, 2-info, 3-warn, 4-err, 5-crit, 6-off
pjsip=1               ; PJSIP library logging level (1 is recommended for debugging, 3-4 for production)
sip_messages=false    ; Dump raw SIP messages (INVITE, BYE, SDP). Useful for network debugging if pjsip=1

console_min_level=0   ; Minimum log level to be written to the console (stdout)
file_min_level=0      ; Minimum log level to be written to the log file

tdlib=5          ; Telegram (TDLib) logging level. Written to file only, unaffected by other settings.
                 ; 0-fatal, 1-errors, 2-warnings, 3-info, 4-debug, 5-verbose debug (huge amount of data)

[telegram]
api_id=                              ; Application identifier (App ID) from my.telegram.org
api_hash=                            ; Application hash (App Hash) from my.telegram.org

system_language_code=                     ; IETF language tag of the host OS passed to Telegram servers
device_model=                          ; Device model. Can be customized
system_version=                       ; OS version displayed in active Telegram sessions
application_version=                   ; Displayed version of your custom gateway/client

;use_proxy=                             ; Use a SOCKS5 proxy for main Telegram traffic (MTProto)
;proxy_address=
;proxy_port=0
;proxy_username=
;proxy_password=

;use_voip_proxy=                        ; Use a separate SOCKS5 proxy for voice traffic (WebRTC)
;voip_proxy_address=
;voip_proxy_port=0
;voip_proxy_username=
;voip_proxy_password=

[sip]
public_address=                 ; IP address to bind the PJSIP UDP transport
port=                              ; Local SIP port of the gateway 
;stun_server=                          ; STUN server for NAT traversal on the SIP side

callback_uri=sip:tg@127.0.0.1:5060      ; SIP URI where the gateway will route incoming Telegram calls
id_uri=sip:tg@127.0.0.1                ; Address of Record (AOR) of the gateway itself.

thread_count=1                         ; Number of PJSIP worker threads to handle media.

[tgcalls]
force_version=auto            ; tgcalls signaling protocol version (auto allows dynamic adaptation to clients)
enable_stun_marking=true      ; Enables DSCP packet marking for prioritizing voice traffic on routers (QoS)

enable_aec=false              ; (Acoustic Echo Cancellation) - Disabled
enable_ns=false               ; (Noise Suppression) - Disabled
enable_agc=false              ; (Automatic Gain Control) - Disabled
volume_control_enabled=false  ; Software volume level control - Disabled

log_path=werbrtc_tgcalls_log        ; File path to write internal WebRTC engine logs (ICE events, BWE, SDP)
stats_log_path=webrtc_tgcalls_stats ; File path to write bitrate, jitter, and packet loss statistics (in JSON format)